import type { Instructor, Ficha, Ambiente, Competencia, HorarioEntry } from '../types';

export const INITIAL_INSTRUCTORES: Instructor[] = [
  {
    id: 'inst-1',
    documento: '1023456789',
    nombre: 'Ing. Carlos Alberto Morales Gómez',
    email: 'cmorales@sena.edu.co',
    telefono: '3104567890',
    especialidad: 'Desarrollo de Software & Algoritmia',
    vinculacion: 'Planta',
    maxHorasSemanales: 32,
    color: '#10B981',
    diasDisponibles: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
    jornadasDisponibles: ['Mañana', 'Tarde'],
  },
  {
    id: 'inst-2',
    documento: '1088765432',
    nombre: 'Dra. María Fernanda Restrepo López',
    email: 'mrestrepo@sena.edu.co',
    telefono: '3157891234',
    especialidad: 'Bases de Datos & Arquitectura Cloud',
    vinculacion: 'Contratista',
    maxHorasSemanales: 40,
    color: '#3B82F6',
    diasDisponibles: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
    jornadasDisponibles: ['Mañana', 'Tarde', 'Noche'],
  },
  {
    id: 'inst-3',
    documento: '71987654',
    nombre: 'Esp. Jorge Eliécer Ramírez Vargas',
    email: 'jramirez@sena.edu.co',
    telefono: '3182345678',
    especialidad: 'Infraestructura, Redes & Seguridad',
    vinculacion: 'Planta',
    maxHorasSemanales: 32,
    color: '#8B5CF6',
    diasDisponibles: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
    jornadasDisponibles: ['Mañana', 'Tarde'],
  },
  {
    id: 'inst-4',
    documento: '52345678',
    nombre: 'Lic. Diana Patricia Mendoza Castillo',
    email: 'dmendoza@sena.edu.co',
    telefono: '3129876543',
    especialidad: 'Competencias Clave - Inglés Técnico',
    vinculacion: 'Contratista',
    maxHorasSemanales: 40,
    color: '#EC4899',
    diasDisponibles: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
    jornadasDisponibles: ['Mañana', 'Tarde', 'Noche'],
  },
  {
    id: 'inst-5',
    documento: '80123456',
    nombre: 'Mg. Andrés Felipe Castro Salazar',
    email: 'acastro@sena.edu.co',
    telefono: '3161234567',
    especialidad: 'Frontend, UX/UI & Aplicaciones Móviles',
    vinculacion: 'Contratista',
    maxHorasSemanales: 40,
    color: '#F59E0B',
    diasDisponibles: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
    jornadasDisponibles: ['Tarde', 'Noche'],
  },
  {
    id: 'inst-6',
    documento: '43987123',
    nombre: 'Esp. Sandra Milena Ortiz Henao',
    email: 'sortiz@sena.edu.co',
    telefono: '3008765432',
    especialidad: 'Ética, Comunicación y Liderazgo',
    vinculacion: 'Planta',
    maxHorasSemanales: 32,
    color: '#06B6D4',
    diasDisponibles: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
    jornadasDisponibles: ['Mañana', 'Tarde', 'Noche'],
  }
];

export const INITIAL_FICHAS: Ficha[] = [
  {
    id: 'ficha-1',
    codigo: '2670123',
    nombrePrograma: 'Tecnólogo en Análisis y Desarrollo de Software (ADSO)',
    nivelFormacion: 'Tecnólogo',
    jornada: 'Mañana',
    trimestre: 3,
    totalAprendices: 28,
    sede: 'Centro de Teleinformática y Producción',
    diasFormacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
  },
  {
    id: 'ficha-2',
    codigo: '2670456',
    nombrePrograma: 'Tecnólogo en Gestión de Redes de Datos',
    nivelFormacion: 'Tecnólogo',
    jornada: 'Mañana',
    trimestre: 2,
    totalAprendices: 24,
    sede: 'Centro de Teleinformática y Producción',
    diasFormacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
  },
  {
    id: 'ficha-3',
    codigo: '2710890',
    nombrePrograma: 'Tecnólogo en Análisis y Desarrollo de Software (ADSO) - Tarde',
    nivelFormacion: 'Tecnólogo',
    jornada: 'Tarde',
    trimestre: 1,
    totalAprendices: 30,
    sede: 'Centro de Teleinformática y Producción',
    diasFormacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
  },
  {
    id: 'ficha-4',
    codigo: '2820555',
    nombrePrograma: 'Técnico en Programación de Aplicaciones para Dispositivos Móviles',
    nivelFormacion: 'Técnico',
    jornada: 'Noche',
    trimestre: 2,
    totalAprendices: 22,
    sede: 'Centro de Teleinformática y Producción',
    diasFormacion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
  }
];

export const INITIAL_AMBIENTES: Ambiente[] = [
  {
    id: 'amb-1',
    codigo: 'Ambiente 301',
    nombre: 'Laboratorio de Desarrollo de Software FullStack',
    sede: 'Bloque B - Piso 3',
    tipo: 'Sistemas / Cómputo',
    capacidad: 32,
    equiposDisponibles: 30,
  },
  {
    id: 'amb-2',
    codigo: 'Ambiente 302',
    nombre: 'Laboratorio de Arquitectura y Base de Datos',
    sede: 'Bloque B - Piso 3',
    tipo: 'Sistemas / Cómputo',
    capacidad: 30,
    equiposDisponibles: 28,
  },
  {
    id: 'amb-3',
    codigo: 'Ambiente 204',
    nombre: 'Taller de Infraestructura de Redes & Telecomunicaciones',
    sede: 'Bloque A - Piso 2',
    tipo: 'Laboratorio Redes',
    capacidad: 26,
    equiposDisponibles: 25,
  },
  {
    id: 'amb-4',
    codigo: 'Ambiente 105',
    nombre: 'Aula Multimedial de Idiomas & Bilingüismo',
    sede: 'Bloque C - Piso 1',
    tipo: 'Aula Convencional',
    capacidad: 35,
    equiposDisponibles: 20,
  },
  {
    id: 'amb-5',
    codigo: 'Ambiente 401',
    nombre: 'Laboratorio Móvil e Interacción UX/UI',
    sede: 'Bloque B - Piso 4',
    tipo: 'Sistemas / Cómputo',
    capacidad: 28,
    equiposDisponibles: 26,
  },
  {
    id: 'amb-6',
    codigo: 'Auditorio Principal',
    nombre: 'Auditorio Polivalente de Conferencias y Ética',
    sede: 'Bloque Central',
    tipo: 'Auditorio / Polivalente',
    capacidad: 80,
  }
];

export const INITIAL_COMPETENCIAS: Competencia[] = [
  // Ficha 1 - ADSO Mañana
  {
    id: 'comp-101',
    codigo: '220501096',
    nombre: 'Desarrollar la solución de software de acuerdo con el diseño y metodologías de desarrollo',
    resultadoAprendizaje: 'Construir el backend y servicios REST aplicando patrones arquitectónicos',
    fichaId: 'ficha-1',
    instructorId: 'inst-1',
    ambienteId: 'amb-1',
    horasSemanales: 8,
    horasTotales: 96,
    bloqueMinimoHoras: 4,
  },
  {
    id: 'comp-102',
    codigo: '220501095',
    nombre: 'Diseñar la estructura de la base de datos según requerimientos del cliente',
    resultadoAprendizaje: 'Crear el modelo relacional y scripts DDL/DML en motor PostgreSQL',
    fichaId: 'ficha-1',
    instructorId: 'inst-2',
    ambienteId: 'amb-2',
    horasSemanales: 8,
    horasTotales: 96,
    bloqueMinimoHoras: 4,
  },
  {
    id: 'comp-103',
    codigo: '240202501',
    nombre: 'Interactuar en lengua inglesa de forma oral y escrita en contextos laborales y académicos',
    resultadoAprendizaje: 'Comprender vocabulario técnico de software y documentación en inglés',
    fichaId: 'ficha-1',
    instructorId: 'inst-4',
    ambienteId: 'amb-4',
    horasSemanales: 6,
    horasTotales: 72,
    bloqueMinimoHoras: 3,
  },
  {
    id: 'comp-104',
    codigo: '240201526',
    nombre: 'Enriquecer el proyecto de vida con base en principios y valores éticos',
    resultadoAprendizaje: 'Promover la convivencia y el trabajo colaborativo en el entorno productivo',
    fichaId: 'ficha-1',
    instructorId: 'inst-6',
    ambienteId: 'amb-6',
    horasSemanales: 4,
    horasTotales: 48,
    bloqueMinimoHoras: 2,
  },

  // Ficha 2 - Redes Mañana
  {
    id: 'comp-201',
    codigo: '220501012',
    nombre: 'Implementar la estructura de la red cableada e inalámbrica según normas técnicas internacionales',
    resultadoAprendizaje: 'Configurar switches, routers y VLANs para la topología empresarial',
    fichaId: 'ficha-2',
    instructorId: 'inst-3',
    ambienteId: 'amb-3',
    horasSemanales: 10,
    horasTotales: 120,
    bloqueMinimoHoras: 3,
  },
  {
    id: 'comp-202',
    codigo: '240202501',
    nombre: 'Interactuar en lengua inglesa de forma oral y escrita en contextos laborales y académicos',
    resultadoAprendizaje: 'Interpretar manuales de networking y configuraciones en inglés',
    fichaId: 'ficha-2',
    instructorId: 'inst-4',
    ambienteId: 'amb-4',
    horasSemanales: 6,
    horasTotales: 72,
    bloqueMinimoHoras: 3,
  },
  {
    id: 'comp-203',
    codigo: '240201526',
    nombre: 'Enriquecer el proyecto de vida con base en principios y valores éticos',
    resultadoAprendizaje: 'Liderar equipos de soporte y mantenimiento con ética profesional',
    fichaId: 'ficha-2',
    instructorId: 'inst-6',
    ambienteId: 'amb-6',
    horasSemanales: 4,
    horasTotales: 48,
    bloqueMinimoHoras: 2,
  },

  // Ficha 3 - ADSO Tarde
  {
    id: 'comp-301',
    codigo: '220501093',
    nombre: 'Evaluar requisitos de la solución de software de acuerdo con estándares y requerimientos',
    resultadoAprendizaje: 'Levantar requerimientos funcionales y no funcionales con historias de usuario',
    fichaId: 'ficha-3',
    instructorId: 'inst-1',
    ambienteId: 'amb-1',
    horasSemanales: 8,
    horasTotales: 96,
    bloqueMinimoHoras: 4,
  },
  {
    id: 'comp-302',
    codigo: '220501096',
    nombre: 'Desarrollar la solución de software de acuerdo con el diseño y metodologías de desarrollo',
    resultadoAprendizaje: 'Programar interfaces de usuario frontend interactivas con React',
    fichaId: 'ficha-3',
    instructorId: 'inst-5',
    ambienteId: 'amb-5',
    horasSemanales: 10,
    horasTotales: 120,
    bloqueMinimoHoras: 3,
  },
  {
    id: 'comp-303',
    codigo: '240202501',
    nombre: 'Interactuar en lengua inglesa de forma oral y escrita en contextos laborales y académicos',
    resultadoAprendizaje: 'Comunicarse en reuniones de scrum y entregas de sprint en inglés',
    fichaId: 'ficha-3',
    instructorId: 'inst-4',
    ambienteId: 'amb-4',
    horasSemanales: 6,
    horasTotales: 72,
    bloqueMinimoHoras: 3,
  },

  // Ficha 4 - Apps Móviles Noche
  {
    id: 'comp-401',
    codigo: '220501097',
    nombre: 'Construir aplicaciones móviles nativas e híbridas según diseño y plataformas objetivo',
    resultadoAprendizaje: 'Desarrollar aplicaciones Android y Flutter integradas con APIs en la nube',
    fichaId: 'ficha-4',
    instructorId: 'inst-5',
    ambienteId: 'amb-5',
    horasSemanales: 10,
    horasTotales: 120,
    bloqueMinimoHoras: 2,
  },
  {
    id: 'comp-402',
    codigo: '220501095',
    nombre: 'Diseñar la estructura de la base de datos según requerimientos del cliente',
    resultadoAprendizaje: 'Implementar bases de datos SQLite y Firestore para apps móviles',
    fichaId: 'ficha-4',
    instructorId: 'inst-2',
    ambienteId: 'amb-2',
    horasSemanales: 8,
    horasTotales: 96,
    bloqueMinimoHoras: 2,
  }
];

export const INITIAL_HORARIOS: HorarioEntry[] = [
  // Horarios Ficha 1 (ADSO Mañana)
  {
    id: 'hor-1',
    fichaId: 'ficha-1',
    competenciaId: 'comp-101',
    instructorId: 'inst-1',
    ambienteId: 'amb-1',
    dia: 'Lunes',
    horaInicio: 6,
    duracionHoras: 4,
    observaciones: 'Sesión práctica de Backend y APIs'
  },
  {
    id: 'hor-2',
    fichaId: 'ficha-1',
    competenciaId: 'comp-104',
    instructorId: 'inst-6',
    ambienteId: 'amb-6',
    dia: 'Lunes',
    horaInicio: 10,
    duracionHoras: 2,
    observaciones: 'Taller de Ética y Liderazgo'
  },
  {
    id: 'hor-3',
    fichaId: 'ficha-1',
    competenciaId: 'comp-102',
    instructorId: 'inst-2',
    ambienteId: 'amb-2',
    dia: 'Martes',
    horaInicio: 6,
    duracionHoras: 4,
    observaciones: 'Modelado y normalización SQL'
  },
  {
    id: 'hor-4',
    fichaId: 'ficha-1',
    competenciaId: 'comp-103',
    instructorId: 'inst-4',
    ambienteId: 'amb-4',
    dia: 'Martes',
    horaInicio: 10,
    duracionHoras: 2,
    observaciones: 'Bilingüismo técnico'
  },
  {
    id: 'hor-5',
    fichaId: 'ficha-1',
    competenciaId: 'comp-101',
    instructorId: 'inst-1',
    ambienteId: 'amb-1',
    dia: 'Miércoles',
    horaInicio: 6,
    duracionHoras: 4,
    observaciones: 'Desarrollo de servicios REST y JWT'
  },
  {
    id: 'hor-6',
    fichaId: 'ficha-1',
    competenciaId: 'comp-104',
    instructorId: 'inst-6',
    ambienteId: 'amb-6',
    dia: 'Miércoles',
    horaInicio: 10,
    duracionHoras: 2,
    observaciones: 'Trabajo en equipo y proyectos'
  },
  {
    id: 'hor-7',
    fichaId: 'ficha-1',
    competenciaId: 'comp-102',
    instructorId: 'inst-2',
    ambienteId: 'amb-2',
    dia: 'Jueves',
    horaInicio: 6,
    duracionHoras: 4,
    observaciones: 'Procedimientos almacenados y triggers'
  },
  {
    id: 'hor-8',
    fichaId: 'ficha-1',
    competenciaId: 'comp-103',
    instructorId: 'inst-4',
    ambienteId: 'amb-4',
    dia: 'Viernes',
    horaInicio: 6,
    duracionHoras: 4,
    observaciones: 'Reading technical docs & Speaking'
  },

  // Horarios Ficha 2 (Redes Mañana)
  {
    id: 'hor-9',
    fichaId: 'ficha-2',
    competenciaId: 'comp-201',
    instructorId: 'inst-3',
    ambienteId: 'amb-3',
    dia: 'Lunes',
    horaInicio: 6,
    duracionHoras: 4,
    observaciones: 'Cableado estructurado y ponchado'
  },
  {
    id: 'hor-10',
    fichaId: 'ficha-2',
    competenciaId: 'comp-202',
    instructorId: 'inst-4',
    ambienteId: 'amb-4',
    dia: 'Lunes',
    horaInicio: 10,
    duracionHoras: 2,
    observaciones: 'Inglés técnico para redes'
  },
  {
    id: 'hor-11',
    fichaId: 'ficha-2',
    competenciaId: 'comp-201',
    instructorId: 'inst-3',
    ambienteId: 'amb-3',
    dia: 'Miércoles',
    horaInicio: 6,
    duracionHoras: 4,
    observaciones: 'Configuración Packet Tracer y Switches Cisco'
  },
  {
    id: 'hor-12',
    fichaId: 'ficha-2',
    competenciaId: 'comp-203',
    instructorId: 'inst-6',
    ambienteId: 'amb-6',
    dia: 'Jueves',
    horaInicio: 6,
    duracionHoras: 4,
    observaciones: 'Resolución de conflictos en el trabajo'
  },
  {
    id: 'hor-13',
    fichaId: 'ficha-2',
    competenciaId: 'comp-202',
    instructorId: 'inst-4',
    ambienteId: 'amb-4',
    dia: 'Jueves',
    horaInicio: 10,
    duracionHoras: 2,
    observaciones: 'Glosario de protocolos'
  },
  {
    id: 'hor-14',
    fichaId: 'ficha-2',
    competenciaId: 'comp-201',
    instructorId: 'inst-3',
    ambienteId: 'amb-3',
    dia: 'Viernes',
    horaInicio: 8,
    duracionHoras: 2,
    observaciones: 'Pruebas de latencia y throughput'
  },

  // Horarios Ficha 3 (ADSO Tarde)
  {
    id: 'hor-15',
    fichaId: 'ficha-3',
    competenciaId: 'comp-301',
    instructorId: 'inst-1',
    ambienteId: 'amb-1',
    dia: 'Lunes',
    horaInicio: 12,
    duracionHoras: 4,
    observaciones: 'Levantamiento de diagramas UML'
  },
  {
    id: 'hor-16',
    fichaId: 'ficha-3',
    competenciaId: 'comp-302',
    instructorId: 'inst-5',
    ambienteId: 'amb-5',
    dia: 'Martes',
    horaInicio: 12,
    duracionHoras: 5,
    observaciones: 'Fundamentos de React y componentes'
  },
  {
    id: 'hor-17',
    fichaId: 'ficha-3',
    competenciaId: 'comp-301',
    instructorId: 'inst-1',
    ambienteId: 'amb-1',
    dia: 'Miércoles',
    horaInicio: 12,
    duracionHoras: 4,
    observaciones: 'Casos de uso y prototipado Figma'
  },
  {
    id: 'hor-18',
    fichaId: 'ficha-3',
    competenciaId: 'comp-302',
    instructorId: 'inst-5',
    ambienteId: 'amb-5',
    dia: 'Jueves',
    horaInicio: 12,
    duracionHoras: 5,
    observaciones: 'Hooks, Estados y llamadas a Backend'
  },
  {
    id: 'hor-19',
    fichaId: 'ficha-3',
    competenciaId: 'comp-303',
    instructorId: 'inst-4',
    ambienteId: 'amb-4',
    dia: 'Viernes',
    horaInicio: 12,
    duracionHoras: 4,
    observaciones: 'Daily meetings y demos en inglés'
  },

  // Horarios Ficha 4 (Móviles Noche)
  {
    id: 'hor-20',
    fichaId: 'ficha-4',
    competenciaId: 'comp-401',
    instructorId: 'inst-5',
    ambienteId: 'amb-5',
    dia: 'Lunes',
    horaInicio: 18,
    duracionHoras: 4,
    observaciones: 'Introducción a Flutter y Widgets'
  },
  {
    id: 'hor-21',
    fichaId: 'ficha-4',
    competenciaId: 'comp-402',
    instructorId: 'inst-2',
    ambienteId: 'amb-2',
    dia: 'Martes',
    horaInicio: 18,
    duracionHoras: 4,
    observaciones: 'Base de datos NoSQL y SQLite'
  },
  {
    id: 'hor-22',
    fichaId: 'ficha-4',
    competenciaId: 'comp-401',
    instructorId: 'inst-5',
    ambienteId: 'amb-5',
    dia: 'Miércoles',
    horaInicio: 18,
    duracionHoras: 3,
    observaciones: 'Navegación y consumo de API REST'
  },
  {
    id: 'hor-23',
    fichaId: 'ficha-4',
    competenciaId: 'comp-402',
    instructorId: 'inst-2',
    ambienteId: 'amb-2',
    dia: 'Jueves',
    horaInicio: 18,
    duracionHoras: 4,
    observaciones: 'Autenticación con Firebase'
  },
  {
    id: 'hor-24',
    fichaId: 'ficha-4',
    competenciaId: 'comp-401',
    instructorId: 'inst-5',
    ambienteId: 'amb-5',
    dia: 'Viernes',
    horaInicio: 18,
    duracionHoras: 3,
    observaciones: 'Publicación y empaquetado APK'
  }
];
